using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DawnOfLight.GameServer.Constants
{
    public enum eEncryptionState
    {
        NotEncrypted = 0,
        RSAEncrypted = 1,
        PseudoRC4Encrypted = 2
    }

    public enum PacketType
    {
        TCP = 0x01,
        UDP = 0x02
    }

    public enum ClientStatus
    {
        None = 0,
        LoggedIn = 1,
        PlayerInGame = 2
    }

    public enum ServerPackets : byte
    {
        InventoryUpdate = 0x02,
        HouseUserPermissions = 0x03,
        CharacterJump = 0x04,
        HousingPermissions = 0x05,
        HouseEnter = 0x08,
        HousingItem = 0x09,
        HouseExit = 0x0A,
        HouseTogglePoints = 0x0F,
        MovingObjectCreate = 0x12,
        EquipmentUpdate = 0x15,
        VariousUpdate = 0x16,
        MerchantWindow = 0x17,
        HouseDecorationRotate = 0x18,
        SpellEffectAnimation = 0x1B,
        ConsignmentMerchantMoney = 0x1E,
        MarketExplorerWindow = 0x1F,
        PositionAndObjectID = 0x20,
        DebugMode = 0x21,
        CryptKey = 0x22,
        SessionID = 0x28,
        PingReply = 0x29,
        LoginGranted = 0x2A,
        CharacterInitFinished = 0x2B,
        LoginDenied = 0x2C,
        GameOpenReply = 0x2D,
        UDPInitReply = 0x2F,
        MinotaurRelicMapRemove = 0x45,
        MinotaurRelicMapUpdate = 0x46,
        WarMapClaimedKeeps = 0x49,
        WarMapDetailUpdate = 0x4A,
        PlayerCreate172 = 0x4B,
        VisualEffect = 0x4C,
        ControlledHorse = 0x4E,
        MinotaurRelicRealm = 0x59,
        XFire = 0x5C,
        KeepComponentInteractResponse = 0x61,
        KeepClaim = 0x62,
        KeepComponentHookpointStore = 0x63,
        KeepComponentHookpointUpdate = 0x65,
        WarmapBonuses = 0x66,
        KeepComponentUpdate = 0x67,
        KeepInfo = 0x69,
        KeepRealmUpdate = 0x6A,
        KeepRemove = 0x6B,
        KeepComponentInfo = 0x6C,
        KeepComponentDetailUpdate = 0x6D,
        GroupMemberUpdate = 0x70,
        SpellCastAnimation = 0x72,
        InterruptSpellCast = 0x73,
        AttackMode = 0x74,
        ConcentrationList = 0x75,
        TrainerWindow = 0x7B,
        Time = 0x7E,
        UpdateIcons = 0x7F,
        Dialog = 0x81,
        QuestEntry = 0x83,
        FindGroupUpdate = 0x86,
        PetWindow = 0x88,
        PlayerRevive = 0x89,
        PlayerModelTypeChange = 0x8D,
        CharacterPointsUpdate = 0x91,
        Weather = 0x92,
        DoorState = 0x99,
        ClientRegions = 0x9E,
        ObjectUpdate = 0xA1,
        RemoveObject = 0xA2,
        Quit = 0xA4,
        PlayerPosition = 0xA9,
        CharacterStatusUpdate = 0xAD,
        PlayerDeath = 0xAE,
        Message = 0xAF,
        MaxSpeed = 0xB6,
        RegionChanged = 0xB7,
        PlayerHeading = 0xBA,
        CombatAnimation = 0xBC,
        Encumberance = 0xBD,
        BadNameCheckReply = 0xC3,
        DetailWindow = 0xC4,
        AddFriend = 0xC5,
        RemoveFriend = 0xC6,
        Riding = 0xC8,
        SoundEffect = 0xC9,
        DupNameCheckReply = 0xCC,
        HouseCreate = 0xD1,
        HouseChangeGarden = 0xD2,
        PlaySound = 0xD3,
        PlayerCreate = 0xD4,
        DisableSkills = 0xD6,
        DelveInfo = 0xD8,
        ObjectCreate = 0xD9,
        NPCCreate = 0xDA,
        ModelChange = 0xDB,
        ObjectGuildID = 0xDE,
        ChangeGroundTarget = 0xDF,
        ObjectDelete = 0xE1,
        EmblemDialogue = 0xE2,
        SiegeWeaponAnimation = 0xE3,
        TradeWindow = 0xEA,
        ObjectDataUpdate = 0xEE,
        RegionSound = 0xEF,
        CharacterCreateReply = 0xF0,
        TimerWindow = 0xF3,
        SiegeWeaponInterface = 0xF5,
        ChangeTarget = 0xF6,
        HelpWindow = 0xF7,
        EmoteAnimation = 0xF9,
        MoneyUpdate = 0xFA,
        StatsUpdate = 0xFB,
        CharacterOverview = 0xFD,
        Realm = 0xFE,
        MasterLevelWindow = 0x13,
    }

    public enum ClientPackets : byte
    {
        PlayerCancelsEffect = 0xF8,
        PlayerAttackRequest = 0x74,
        PlayerAppraiseItemRequest = 0xE0,
        PetWindow = 0x8A,
        ObjectInteractRequest = 0x7A,
        InviteToGroup = 0x87,
        HouseEnterLeave = 0x0B,
        DoorRequest = 0x99,
        DisbandFromGroup = 0xA8,
        DialogResponse = 0x82,
        CheckLOSRequest = 0xD0,
        WorldInitRequest = 0xD4,
        UseSpell = 0x7D,
        UseSlot = 0x71,
        UseSkill = 0xBB,
        RemoveConcentrationEffect = 0x76,
        PlayerRegionChangeRequest = 0x90,
        QuestRewardChosen = 0x40,
        PlayerTarget = 0xB0,
        PlayerSitRequest = 0xC7,
        PlayerInitRequest = 0xE8,
        PlayerGroundTarget = 0xEC,
        PlayerDismountRequest = 0xC8,
        PlayerHeadingUpdate = 0xBA,
        PlayerPickupHouseItem = 0x0D,
        PlayerMoveItem = 0xDD,
        BadNameCheckRequest = 0xC2,
        HousingMenuRequest = 0x00,
        BuyHookPoint = 0x64,
        CharacterCreateRequest = 0xFF,
        CharacterDeleteRequest = 0xC0,
        CharacterOverviewRequest = 0xFC,
        CharacterSelectRequest = 0x10,
        ClientCrash = 0x37,
        CryptKeyRequest = 0xF4,
        DestroyItemRequest = 0x80,
        DuplicateNameCheckRequest = 0xCB,
        EmblemDialogReponse = 0xE2,
        GameOpenRequest = 0xBF,
        DetailDisplay = 0xD8,
        HouseEdit = 0x01,
        HousePermissionsRequest = 0x05,
        HousePermissionsSet = 0x07,
        HouseUsersPermissionsRequest = 0x03,
        HouseUsersPermissionsSet = 0x06,
        HousingDecorationRotate = 0x0E,
        HousingDecorationRotateRequest = 0x18,
        HousingPlaceItem = 0x0C,
        KeepComponentInteract = 0x6F,
        LoginRequest = 0xA7,
        LookingForAGroupFlag = 0x84,
        LookingForAGroup = 0x85,
        MakeProduct = 0xED,
        MinotaurRelicWindow = 0x4C,
        NPCCreationRequest = 0xBE,
        ObjectUpdateRequest = 0xA5,
        PingRequest = 0xA3,
        PlayerBonusesListRequest = 0xCA,
        PlayerBuyRequest = 0x78,
        PlayerCommand = 0xAF,
        PlayerCreationRequest = 0xD5,
        PlayerTrain = 0x83,
        PlayerTrainWindow = 0x7B,
        PlayerTrainRequest = 0x7C,
        PlayerMarketSearchRequest = 0x11,
        PlayerModifyTrade = 0xEB,
        PlayerPickUpRequest = 0xB5,
        PlayerPositionUpdate = 0xA9,
        PlayerSellRequest = 0x79,
        PlayerSetMarketPrice = 0x1A,
        PlayerWithdrawMerchantMoney = 0x1C,
        QuestRemoveRequest = 0x4F,
        RegionListRequest = 0x9D,
        ShipHookpointInteract = 0xE4,
        SiegeWeaponAction = 0xF5,
        UDPInitRequest = 0x14,
        UDPPingRequest = 0xF2,
        WarMapBonusesRequest = 0x66,
        WarMapShowRequest = 0x48
    }
}
